# import = [
#     "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
# ]
[shell]
args = ['-l']
program = "/bin/zsh"

# [cursor]
# style = {shape ="Beam",blinking = "Never"}
# vi_mode_style ={shape ="Beam",blinking = "Never"}
[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Hack Nerd Font"

[window]
option_as_alt="Both"
position = { x = 200, y = 65 }
dimensions={columns=180,lines=51}
# dynamic_padding = true
opacity = 0.95
blur = true
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
decorations = 'buttonless'




# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#24283b'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

