import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]
[shell]
args = ['-l']
program = "/bin/zsh"

# [cursor]
# style = {shape ="Beam",blinking = "Never"}
# vi_mode_style ={shape ="Beam",blinking = "Never"}
[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "Hack Nerd Font"

[window]
option_as_alt="Both"
position = { x = 100, y = 0 }
dimensions={columns=180,lines=58}
dynamic_padding = true
opacity = 1
blur = false
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
# decorations = 'buttonless'

# opacity = 1
# blur = true
# [window.padding]
# x = 6
# y = 10


# [colors.normal]
# black = "0x2e3436"
# red = "0xcc0000"
# green = "0x73d216"
# yellow = "0xedd400"
# blue = "0x3465a4"
# magenta = "0x75507b"
# cyan = "0x06989a"
# white = "0xd3d7cf"

# [colors.bright]
#  black=   '0x2e3436'
#  red=     '0xef2929'
#  green=   '0x8ae234'
#  yellow=  '0xfce94f'
#  blue=    '0x729fcf'
#  magenta= '0xad7fa8'
#  cyan=    '0x34e2e2'
#  white=   '0xeeeeec'

# [colors.primary]
# background = "#282a36"
# foreground = "0xeeeeec"

# [colors.cursor]
# text = "CellBackground"
# cursor = "CellForeground"

